### ISSUE TITLE
django 3.0  and whitenoise 3.3.1 incompatible

### ISSUE THREAD

**Issue by jensdoecke** [Kivou-2000607/yata#187]
Which Django Version do you use? With the current Django Relase it doesn't work with whitenoise because of the module six. As Quickfix a lock of the Django-Version in requirements.txt would be okay.

Currently I'm trying to migrate to whitenoise-5.0.1. But I'm feeling there is a good reason you stay on whitenoise 3.3.1. If I'm lucky with the migration, I'll do a pull request. :)

Some Informations of my try to run the server.

Requirements:
Requirement already satisfied: Django>=2.0 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (3.0)
Requirement already satisfied: whitenoise==3.3.1 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 7)) (3.3.1)

Stacktrace:
(venv)  ✘  ~/ws/yata   master  python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
December 17, 2019 - 10:27:10
Django version 3.0, using settings 'yata.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/jens/ws/yata/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 45, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/jens/ws/yata/venv/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jens/ws/yata/yata/wsgi.py", line 13, in <module>
    from whitenoise.django import DjangoWhiteNoise
  File "/home/jens/ws/yata/venv/lib/python3.6/site-packages/whitenoise/django.py", line 18, in <module>
    from django.utils.six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'django.utils.six'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jens/ws/yata/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/jens/ws/yata/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/jens/ws/yata/venv/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/home/jens/ws/yata/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/jens/ws/yata/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 50, in get_internal_wsgi_application
    ) from err
django.core.exceptions.ImproperlyConfigured: WSGI application 'yata.wsgi.application' could not be loaded; Error importing module.

**Comment by Kivou-2000607** [comment]
Yes I know. I fixed it on a version I didn't push.
I'm on Django==2.2.7

I was waiting for version 3 that has been released a couple of weeks ago

**Comment by jensdoecke** [comment]
OK, works right now. I had some issues with initial setup (AwardsData/News) but now I can work with the it. If you need some help, I'm jdo_O (2200962) and full time dev (in discord/torn).

**Comment by Kivou-2000607** [comment]
I have to make a setup script I know ^^
Or handle void database calls everywhere.
